# This Dockerfile is intended mainly for running the tests and building
# distribution packages/artifacts. It isn’t currently useful for using the tool
# because the tool requires access to your clipboard, which is very tricky from
# within a Docker container. That might be changing soon though; we may be
# adding a new file-based workflow soon as our main recommended workflow. If so,
# we could use docker-compose to mount a data directory and run the tool from
# within a container.

FROM quay.io/fundingcircle/clojure-node-chromium:clojure-1.9.0.394_node-11.1_debian-stretch
LABEL maintainer="Avi Flax <avi.flax@fundingcircle.com>"

WORKDIR /tool

# Copy Clojure’s deps.edn and Node’s package files then download the deps
# separately from and prior to copying the app code so that we don’t have to
# re-download deps every time the app code changes.

COPY deps.edn ./
COPY bin/download-clojure-deps bin/
RUN bin/download-clojure-deps

COPY renderer/package*.json ./renderer/
COPY bin/download-node-deps bin/
RUN bin/download-node-deps

# Now copy *all* the code.
COPY . ./
