# This Dockerfile is intended only for running the tests. It isn’t useful for
# using the tool because the tool requires access to your clipboard, which is
# very tricky from within a Docker container.

FROM quay.io/fundingcircle/clojure-node-chromium@sha256:84a563c327d900cbfacbeabf41f941a2395ca55835135f639e8b5d656b8d7c80
LABEL maintainer="Avi Flax <avi.flax@fundingcircle.com>"

WORKDIR /tool

# Copy Clojure’s deps.edn and Node’s package files then download the deps
# separately from and prior to copying the app code so that we don’t have to
# re-download deps every time the app code changes.

COPY deps.edn ./
COPY bin/download-clojure-deps bin/
RUN bin/download-clojure-deps

COPY renderer/package*.json ./renderer/
COPY bin/download-node-deps bin/
RUN bin/download-node-deps

# rlwrap is handy in case we need to run a REPL in a container
RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add --no-cache rlwrap@testing

# Now copy *all* the code.
COPY . ./
